spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shoppingmall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
#  쿼리 파라미터를 로그로 남기는 외부 라이브러리는 시스템 자원을 사용하므로 개발 단계에서는 편하게 사용해도 되지만,
#  운영시스템에 적용하려면 꼭 성능테스트를 하고 사용하기
#  org.hibernate.type: trace